sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abeidahmed/multi-docker-deployment -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abeidahmed/multi-docker-deployment npm run test
